### ISSUE TITLE
Error Clash Verge-rev

### ISSUE THREAD

**Issue by chao921125** [Flik6/getNode#6]
https://github.com/clash-verge-rev/clash-verge-rev
在这个客户端上无法正常导入

**Comment by hsl313** [comment]
proxy 0: unsupport proxy type: vless
我也是提示这个

**Comment by Flik6** [comment]
内核用clash meta

**Comment by hsl313** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/
？

**Comment by hsl313** [comment]
那安卓不能用了！可惜了
